import Config

# Configure your database
config :rogs_game, RogsGame.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "rogs_game_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :rogs_game, RogsGameWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "n+E/lVty15nq1Zkyrr8SB0zsOazwHk2Bwqhxz2rj4GNmEoLl7pZ7GwtNdOvOzkWK",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:rogs_game, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:rogs_game, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :rogs_game, RogsGameWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/rogs_game_web/(?:controllers|live|components|router)/?.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :rogs_game, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# --- 開発環境の共通設定 ---
config :phoenix, :stacktrace_depth, 20
config :phoenix, :plug_init_mode, :runtime

# --- Webサーバーの設定 (ポート番号を動的にする) ---

# 1. ゲームUIアプリ (ShinkankiWeb) - Main Port
config :shinkanki_web, ShinkankiWebWeb.Endpoint,
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT") || "4000")],
  secret_key_base: "Hu4qKBq+x1jC8q4qKBq+x1jC8q4qKBq+x1jC8q4qKBq+x1jC8q4qKBq+x1jC8q4q",
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:shinkanki_web, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:shinkanki_web, ~w(--watch)]}
  ],
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"lib/shinkanki_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# 2. 認証アプリ (RogsIdentity)
config :rogs_identity, RogsIdentityWeb.Endpoint,
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT_ID") || "4001")],
  secret_key_base: "Hu4qKBq+x1jC8q4qKBq+x1jC8q4qKBq+x1jC8q4qKBq+x1jC8q4qKBq+x1jC8q4q",
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: []

# 3. 通信アプリ (RogsComm)
config :rogs_comm, RogsCommWeb.Endpoint,
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT_COMM") || "4002")],
  secret_key_base: "Hu4qKBq+x1jC8q4qKBq+x1jC8q4qKBq+x1jC8q4qKBq+x1jC8q4qKBq+x1jC8q4q",
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: []

# Swoosh設定（開発環境ではAPIクライアントを無効化）
config :swoosh, :api_client, false
